# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f91a16f83fcff2adeb4af9bb0e5b86572020dad742cbbc0c52a9e624ed13d79f87e0eabb6d41cde956e873606b7f18218ef9a9b2f6db66c38d493e55d1a472d

test:
  secret_key_base: 6bcc03982dc6f39a4b3a38b47ec3f3139fd87e9dbf276b84174ac9734152738b4b77f356228e7baacd51908e7f5953fd5a859de0d322383d06f6fbc0dc2678e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
